### ISSUE TITLE
Merge efforts?

### ISSUE THREAD

**Issue by stalniy** [EmixMaxime/cancan#1]
Don't know if it's relevant for you but recently I wrote an authorization library CASL, created a lot of documentation, the idea borrowed from cancan ruby gem as well.

You can read more about it here - https://stalniy.github.io/casl/

And the question is whether you think it'd would be good to concentrate your efforts in helping me to work on CASL?

**Comment by mxmaxime** [comment]
Hello,
Your documentation is great. I don't have documentation, because this repo is really small.
My idea is really straightforward, it's inspired by cancan and Laravel policy.
I will write an example to show you the idea, I don't need database integration ect.

It's a good idea, but ours goals are not the same.

**Comment by stalniy** [comment]
In CASL you can actually build custom rule matcher. So, this is just a guess but I believe that Laravely policy can be converted to a function which returns boolean and then it as a custom `Rule` object:

```js
class PolicyRule {
   constructor(rule) { 
     // rule contains information about subject, actions and conditions
   }

   matches(subject) {
     // this function implements matching logic
   }
}

const ability = new Ability(rules, { Rule: PolicyRule })
```

**Comment by ifahim1000** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
m130535, @skippednote, @ekalinin, @iamv1n, @eskp, @jin10086, @xcarpentier, @mudcrab, @talaatmagdyx, @ajtruex, @maciejkowalski, @bakke92, @JAbdor7, @hades2013, @tylerwince, @uadp, @madenmud, @eonward, @rahulwadi, @aarron-lee

**Comment by stalniy** [comment]
Very nice fishing attempt!
